version: '3.8'
services:

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--requirepass", ""]

  websocket-service:
    build: ../apps/websocket-service
    container_name: websocket-service
    command: ["npx", "nodemon", "--legacy-watch", "--watch", "/app", "index.js"]
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    ports:
      - "4008:4008"
    volumes:
      - ../apps/websocket-service:/app
      - /app/node_modules

  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rc
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
  user-service:
    build: ../apps/user-service
    container_name: user-service
    command: ["npx", "nodemon", "--legacy-watch", "--watch", "/app", "index.js"]
    depends_on:
      - db
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=rc
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - JWT_PRIVATE_KEY_PATH=/app/secrets/private.pem
    ports:
      - "4001:4001"
    volumes:
      - ../apps/user-service:/app
      - /app/node_modules
      - ../secrets/rc-notification-52917-firebase-adminsdk-fbsvc-d9174cc5ec.json:/app/secrets/rc-notification-52917-firebase-adminsdk-fbsvc-d9174cc5ec.json
      - ../secrets/private.pem:/app/secrets/private.pem

    
  order-service:
    build: ../apps/order-service
    container_name: order-service
    command: ["npx", "nodemon", "--legacy-watch", "--watch", "/app", "index.js"]
    depends_on:
      - db
      - user-service
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=rc
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=4001
      - JWT_PUBLIC_KEY_PATH=/app/secrets/public.pem
    ports:
      - "4002:4002"
    volumes:
      - ../apps/order-service:/app
      - /app/node_modules
      - ../secrets/public.pem:/app/secrets/public.pem

  delivery-service:
    build: ../apps/delivery-service
    container_name: delivery-service
    command: ["npx", "nodemon", "--legacy-watch", "--watch", "/app", "index.js"]
    depends_on:
      - order-service
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - ORDER_SERVICE_HOST=order-service
      - ORDER_SERVICE_PORT=4002
      - JWT_PUBLIC_KEY_PATH=/app/secrets/public.pem
    ports:
      - "4003:4003"
    volumes:
      - ../apps/delivery-service:/app
      - /app/node_modules
      - ../secrets/public.pem:/app/secrets/public.pem
  
  locations-service:
    build: ../apps/locations-service
    container_name: locations-service
    command: ["npx", "nodemon", "--legacy-watch", "--watch", "/app", "index.js"]
    depends_on:
      - db
      - user-service
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=rc
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=4001
      - JWT_PUBLIC_KEY_PATH=/app/secrets/public.pem
    ports:
      - "4004:4004"
    volumes:
      - ../apps/locations-service:/app
      - /app/node_modules
      - ../secrets/public.pem:/app/secrets/public.pem


volumes:
  mysql-data:
  redis-data: